spring:
  application:
    name: api-gateway
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.106:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.1.106
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.106:8761/eureka/,http://192.168.1.106:8762/eureka/
server:
  port: 8888
feign:
  httpclient:
    connection-timeout: 30000
env:
  test44
zuul:
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 200000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
